### ISSUE TITLE
Fehler beim konvertieren von history zu influx

### ISSUE THREAD

**Issue by realmeto** [ioBroker/ioBroker.history#196]
Die Übertragung der Daten aus iobroker.history in die Influx-Datenbank (mit history2tb.js) schlägt mit nachfolgender Meldung fehl:

pi@raspbi4:/opt/iobroker/node_modules/iobroker.history/converter $ node history2db.js influxdb.0 info 20201231 /home/pi/history  --logChangesOnly --processNonExistingValuesOnly
Send Data to influxdb.0
Start at 20201231
Use historyDir /home/pi/history
earliesDBValues initialized from cache 135
ExistingDBTypes initialized from cache 135
Started processFiles with 135 known db values
We start earliest at 20201231
Day 20201231 - history.hm-rega.0.51333.json
datapoints reduced from 345 --> 345
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Assignment to constant variable.
at processFile (/opt/iobroker/node_modules/iobroker.history/converter/history2db.js:282:66)
at processFiles (/opt/iobroker/node_modules/iobroker.history/converter/history2db.js:185:5)
at main (/opt/iobroker/node_modules/iobroker.history/converter/history2db.js:148:5)
at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.history/converter/history2db.js:96:5)
at Adapter.emit (node:events:513:28)
at Adapter.emit (node:domain:489:12)
at /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:9132:26

**Comment by realmeto** [comment]
Hab bei mir jetzt zeile 282 von "const jj = 0" in "let jj = 0" geändert. Läuft jetzt gerade noch. Aber  auf jeden Fall nicht gleich in den obigen Fehler.

**Comment by Apollon77** [comment]
genau:-) FIx kommt nachher
