### ISSUE TITLE
Datenübername von history nach influxdb funktioniert nicht

### ISSUE THREAD

**Issue by wdenn** [ioBroker/ioBroker.history#289]
dietpi@server2:/opt/iobroker$ sudo node analyzeinflux.js influxdb.0 info --deepAnalyze
Do deep analysis to find holes in data
InfluxDB-Configuration: {"debounce":1000,"retention":7948800,"dbname":"smarthome","host":"85.215.52.227","protocol":"http","path":"","port":8086,"user":"","organization":"Softwerk","round":4,"seriesBufferMax":0,"seriesBufferFlushInterval":600,"changesRelogInterval":0,"changesMinDelta":0,"reconnectInterval":10000,"pingInterval":15000,"requestTimeout":30000,"validateSSL":true,"dbversion":"2.x","usetags":true,"pingserver":true,"blockTime":0,"debounceTime":0,"disableSkippedValueLogging":false,"enableLogging":false,"customRetentionDuration":365,"relogLastValueOnStart":true}
Query Data from instance "influxdb.0" (Version 2, Bucket smarthome)
Datapoints found: 4
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading 'ts')
    at Object.cb (/opt/iobroker/analyzeinflux.js:143:73)
    at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11102:45)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
    at processImmediate (node:internal/timers:476:21)

ioBroker log:
<html>
<body>

2023-11-25 15:42:43.726 - info: history.0 (19403) starting. Version 3.0.1 in /opt/iobroker/node_modules/iobroker.history, node: v18.18.2, js-controller: 5.0.16
--
2023-11-25 15:42:43.893 - error: history.0 (19403) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-11-25 15:42:43.894 - error: history.0 (19403) unhandled promise rejection: Cannot read properties of undefined (reading 'ts')
2023-11-25 15:42:44.173 - error: history.0 (19403) TypeError: Cannot read properties of undefined (reading 'ts')
at Object.cb (/opt/iobroker/analyzeinflux.js:143:73)
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11102:45)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
at processImmediate (node:internal/timers:476:21)
2023-11-25 15:42:44.174 - error: history.0 (19403) Cannot read properties of undefined (reading 'ts')
2023-11-25 15:42:45.191 - warn: history.0 (19403) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-11-25 15:47:20.606 - info: admin.0 (17154) ==> Connected system.user.admin from ::ffff:192.168.253.15

</body>
</html>

**Comment by Apollon77** [comment]
As said in forum , please add some logging to the file and post the data

**Comment by wdenn** [comment]
Das ioBroker-Log:
<html>
<body>

2023-11-26 10:57:35.745 - info: history.0 (21226) starting. Version 3.0.1 in /opt/iobroker/node_modules/iobroker.history, node: v18.18.2, js-controller: 5.0.16
--
2023-11-26 10:57:35.922 - error: history.0 (21226) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-11-26 10:57:35.923 - error: history.0 (21226) unhandled promise rejection: Cannot read properties of undefined (reading 'ts')
2023-11-26 10:57:36.202 - error: history.0 (21226) TypeError: Cannot read properties of undefined (reading 'ts')
at Object.cb (/opt/iobroker/history/analyzeinflux.js:143:73)
at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11102:45)
at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37)
at processImmediate (node:internal/timers:476:21)
2023-11-26 10:57:36.202 - error: history.0 (21226) Cannot read properties of undefined (reading 'ts')
2023-11-26 10:57:37.220 - warn: history.0 (21226) Terminated (UNCAUGHT_EXCEPTION): Without reason


<br class="Apple-interchange-newline">
</body>
</html>
Die History-Daten werden in Orner mit Datum gespeichert. Hier die aktuellen Daten:
[history.alias.0.Variablen.Energie.verbrauch.json](https://github.com/ioBroker/ioBroker.history/files/13466458/history.alias.0.Variablen.Energie.verbrauch.json)
[history.PV-Produktion.json](https://github.com/ioBroker/ioBroker.history/files/13466460/history.PV-Produktion.json)

Ich hoffe daß Du damit etwas anfangen und mir helfen kannst.
MfG
Willi

**Comment by wdenn** [comment]
> dietpi@server2:/opt/iobroker$ sudo node analyzeinflux.js influxdb.0 info --deepAnalyze Do deep analysis to find holes in data InfluxDB-Configuration: {"debounce":1000,"retention":7948800,"dbname":"smarthome","host":"85.215.52.227","protocol":"http","path":"","port":8086,"user":"","organization":"Softwerk","round":4,"seriesBufferMax":0,"seriesBufferFlushInterval":600,"changesRelogInterval":0,"changesMinDelta":0,"reconnectInterval":10000,"pingInterval":15000,"requestTimeout":30000,"validateSSL":true,"dbversion":"2.x","usetags":true,"pingserver":true,"blockTime":0,"debounceTime":0,"disableSkippedValueLogging":false,"enableLogging":false,"customRetentionDuration":365,"relogLastValueOnStart":true} Query Data from instance "influxdb.0" (Version 2, Bucket smarthome) Datapoints found: 4 This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason: TypeError: Cannot read properties of undefined (reading 'ts') at Object.cb (/opt/iobroker/analyzeinflux.js:143:73) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11102:45) at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37) at processImmediate (node:internal/timers:476:21)
> 
> ioBroker log:
> 
> 2023-11-25 15:42:43.726 - info: history.0 (19403) starting. Version 3.0.1 in /opt/iobroker/node_modules/iobroker.history, node: v18.18.2, js-controller: 5.0.16 -- 2023-11-25 15:42:43.893 - error: history.0 (19403) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 2023-11-25 15:42:43.894 - error: history.0 (19403) unhandled promise rejection: Cannot read properties of undefined (reading 'ts') 2023-11-25 15:42:44.173 - error: history.0 (19403) TypeError: Cannot read properties of undefined (reading 'ts') at Object.cb (/opt/iobroker/analyzeinflux.js:143:73) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11102:45) at Immediate. (/opt/iobroker/node_modules/@iobroker/db-states-redis/src/lib/states/statesInRedisClient.ts:379:37) at processImmediate (node:internal/timers:476:21) 2023-11-25 15:42:44.174 - error: history.0 (19403) Cannot read properties of undefined (reading 'ts') 2023-11-25 15:42:45.191 - warn: history.0 (19403) Terminated (UNCAUGHT_EXCEPTION): Without reason 2023-11-25 15:47:20.606 - info: admin.0 (17154) ==> Connected system.user.admin from ::ffff:192.168.253.15

??????
