### ISSUE TITLE
Error while migrating to SQL

### ISSUE THREAD

**Issue by schdief06** [ioBroker/ioBroker.history#46]
Hi,

I'm trying to move my history to a newly installed SQL database. But when analyzing the database i get the following:

```
/opt/iobroker/node_modules/iobroker.history/converter $ nodejs analyzesql.js sql.0 debug
module.js:550
    throw err;
    ^

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.history/converter/../lib/utils'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.history/converter/analyzesql.js:9:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

I'm not surprised that he doesn't find the file /lib/utis, cause it's not there. xD
But isn't on github neither?

Thanks for helping!

**Comment by Apollon77** [comment]
Please check GitHub version and give feedback

**Comment by schdief06** [comment]
I will try the version tomorrow and let you know, if it worked. Thanks :)

**Comment by schdief06** [comment]
Seems to work

**Comment by Apollon77** [comment]
thx, will come in next version
