### ISSUE TITLE
history2db.js does not find the "common adapter utils"

### ISSUE THREAD

**Issue by Springjunky** [ioBroker/ioBroker.history#59]
Hello,
I try write the history to influx.

My actual path is 
```
/opt/iobroker/node_modules/iobroker.history/converter
```
The following error occurs
```
root@tessa:/opt/iobroker/node_modules/iobroker.history/converter# nodejs history2db.js influxdb.0 20161001 /history
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/opt/iobroker/node_modules/iobroker.history/converter/../lib/utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.history/converter/history2db.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
root@tessa:/opt/iobroker/node_modules/iobroker.history/converter# 
```

This is the same error as described in 
https://www.forum.iobroker.net/topic/3609/history2db-converter/38

**Comment by Springjunky** [comment]
Find the solution by myself :-)
The source in _this_ github repoitory differs in only 1 line
```
const utils   = require('@iobroker/adapter-core'); // Get common adapter utils
```
I have replaced the line 9 with this code above and it works .. seemed to me that the official iobroker repositry has an old source ...

**Comment by Apollon77** [comment]
We just forgot to upgrade these scripts to the new system ... I will do that soon

**Comment by Springjunky** [comment]
keep calm, it's not my productive system :-)

**Comment by Apollon77** [comment]
already in
